### PR TITLE
Dbrooks/setup

### PR DESCRIPTION
**Pull request by djbrooks111**

### CODE REVIEW

**Comment by djbrooks111** [comment]
retest this please

**Comment by djbrooks111** [comment]
retest this please

**Comment by ghost** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">summary file not found</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by ghost** [comment]
[69% (+68.97%) vs master 0%](https://ci.intrepid.io/job/ios-dummy-pr/6/)

**Comment by djbrooks111** [comment]
retest this please

**Comment by djbrooks111** [comment]
retest this please

**Comment by ghost** [comment]
[69% (+68.97%) vs master 0%](https://ci.intrepid.io/job/ios-dummy-pr/8/)

**Pull request merged**
